servers:
  web:
    - <%= ENV.fetch("MORAFEQ_DEMO_SERVER_IP", "192.168.122.29") %>

env:
  clear:
    RAILS_ENV: "demo"
    RAILS_LOG_TO_STDOUT: "1"
    RAILS_SERVE_STATIC_FILES: "true"
    RAILS_MAX_THREADS: "5"
    APP_HOST: <%= ENV.fetch("APP_HOST", "morafeq.hazembook.com") %>
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec -i -e "RAILS_ENV=demo" -- rails console
  shell: app exec -i -- bash
  logs: app logs -f
  dbconsole: app exec -i -e "RAILS_ENV=demo" -- rails dbconsole
